<?php

/**
 * @file drupal module file implementing flot charting.
 */

/**
  * Implementation of hook_chartgraph_provider().
  **/
function charts_graphs_flot_chartgraph_provider() {
  $provider = array(
    'path' => dirname(__FILE__) . '/charts_graphs_flot.class.inc', // must be full path
    'clazz' => 'ChartsGraphsFlot', // implementation class' name
    'name' => 'flot', // name used when invoking through a factory method
    'nice_name' => 'Flot',
    'chart_types' => array(
      'line' => t('Line'),
    ),
  );

  return (object) $provider;
}
